### ISSUE TITLE
Breaks laravel 5.5 schedule run

### ISSUE THREAD

**Issue by bedo-code** [hmazter/laravel-schedule-list#26]
composer require hmazter/laravel-schedule-list results in: 
Warning: Ambiguous class resolution, "Cron\AbstractField"

php artisan schedule:run results in:
In FieldFactory.php line 46:
  5 is not a valid position

**Using laravel 5.5**

**Comment by hmazter** [comment]
Hi, thanks for the report.
Laravel 5.5 depends on the mtdowling/cron-expression package, but Laravel 5.6 and above and my package depend on dragonmantank/cron-expression.
I will see if I can get it to work with both, otherwise the "solution" is to use the `^0.2` tag

**Comment by hmazter** [comment]
Support for Laravel 5.5 has unfortunately been removed since it did not work across the changes of the different framework versions. For Laravel 5.5 please use `^0.2` version
