### ISSUE TITLE
Unable to get cron schedule list through controller

### ISSUE THREAD

**Issue by abetwothree** [hmazter/laravel-schedule-list#30]
For whatever reason I'm unable to get cron schedule through a controller to display on the browser. I have the config file published to my local config folder directory. 

I get the list of cron commands on the command line window. Just not when I try to get them through a controller. 

Not sure if I'm missing something. 

Thank you in advance for your help!

**Comment by hmazter** [comment]
Hi

I was able to replicate the behavior you describe and will try to figure out why that is the case.

**Comment by abetwothree** [comment]
I think there may be a delay in availability of scheduled events. The only way I got it to work on my controller is to manually pass the schedule and console kernel and retriger the schedule list parsing. This is what my function looks like in my controller. 

![image](https://user-images.githubusercontent.com/1899636/55645803-8c821100-57a7-11e9-979a-eed2f4600006.png)

If I remove the type hint resolving of `ScheduleList` from the function it doesn't work though. So I think on the first run the events are not yet available, but since I am resolving the `Schedule` again the events are then available. 

I'm not entirely sure how Laravel handles the scheduled events so I also don't know why there's a race condition.

**Comment by hmazter** [comment]
@skatetdieu Can you test if the PR I just did works for you. It seems to solve the problem for me in an isolated case.

Run this:
```bash
composer require hmazter/laravel-schedule-list dev-30-resolve-schedule-later-to-inlude-events
```

Then you should be able to use `ScheduleList::all` as intended

**Comment by abetwothree** [comment]
Ok, thank you for the update. I will try this soon.
