### ISSUE TITLE
No description visible

### ISSUE THREAD

**Issue by RamonSmit** [hmazter/laravel-schedule-list#4]
Hi there, 

Thanks for this awesome package, It's really helpful in our production environment! 

I have one small problem. The description field is empty under atv least Laravel 5.4 when using the listing. Is there any way to fix this? 

Cheers,
Ramon Smit

**Comment by hmazter** [comment]
Hmm, that's weird. Just checked on one of my production sites and there i see the description when I run `php artisan schedule:list`.

Maybe stupid question, but have you specified a description on the scheduler? This is not the description on the command but the description set by adding `->description('some string')` to the scheduled command. Ex:

```
$schedule->command('inspire')
         ->hourly()
         ->description('Some inspiring words');
```

Let me know if this didn't solve it, and I will see what other thing we can do.

**Comment by RamonSmit** [comment]
Oh gjee. I guess I'm quite blind on this one. 
I'm sorry! Works as it is supposed to be! :-)

(I expected that the package took the `protected $description;`  from the command)

**Comment by hmazter** [comment]
Yeah i would like that that was the functionality =)
But right now I'm limited to use the description that Laravel Schedule exposes, and that is separate from the Command description

**Comment by hmazter** [comment]
FYI from version 0.2.0 the description is now taken from the command. Can be overridden by calling `->description()` on the schedule.

**Comment by RamonSmit** [comment]
Nice :-)! Thanks!
